name: CI for releases

on:
  push:
    branches:
      - master

jobs:
  js-install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v14.17.4]  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies, Test, and Build
      run: |
        yarn install --frozen-lockfile --check-files
      env:
        CI: true

  build-and-push-docker-image:
    needs: [js-install-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}
          repository: techno-tim/littlelink-server
          tags: latest